Components/blog
varya/varya.github.com pull request #103
Opened 2020-11-17 22:57 UTC by Illustrova

Stb: https://5fa818146af67e00217a101f-usopwozqkh.chromatic.com/

2020-11-20 07:57 UTC, varya requested changes

2020-11-20 07:57 UTC, varya commented on src/pages/design-systems/DesignSystems.stories.js
> +    excerpt:
In the Gatsby system, excerpt is not a string but a piece of rendered markdown. At the moment it is inserted like a component with certain parameters:

```
<MDXRenderer onlyExcerpt={true} excerptBackup={excerptClean}>
  {post.body}
</MDXRenderer>
```

Preparing a new component which would display excerpt, you need to make it render a piece of HTML/React components. Maybe like

```
excerpt: (<div>
  Hello world
  </div>),
```

2020-11-22 22:04 UTC, Illustrova commented
Latest storybook: https://5fa818146af67e00217a101f-mohpxualtf.chromatic.com/

2020-11-23 07:54 UTC, varya approved these changes

2020-11-23 15:06 UTC, merged